apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: uphill-prod
spec:
  type: ClusterIP
  selector:
    app: uphill-backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
