apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
      httpMethod: POST

  - name: UphillPostgres
    uid: uphill-postgres
    type: postgres
    access: proxy
    url: db:5432
    user: uphill
    secureJsonData:
      password: uphill_secret
    jsonData:
      database: uphill_ai
      postgresVersion: 1600
      sslmode: disable
