apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: uphill-prod
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        env:
        - name: POSTGRES_DB
          value: uphill_ai
        - name: POSTGRES_USER
          value: uphill
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: uphill-secrets
              key: postgres-password
        ports:
        - containerPort: 5432
          name: dbport
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
